function S = stats_from_binary(I, fs)
I = logical(I(:)); N=numel(I); T=N/fs;
d = diff([false; I; false]); s=find(d==1); e=find(d==-1)-1;
Ne=numel(s); tauF=(e-s+1)/fs;
if Ne>=2, tauG=(s(2:end)-e(1:end-1)-1)/fs; else, tauG=[]; end
S=struct('N',N,'fs',fs,'Tsec',T,'Ne',Ne,'rateHz',Ne/T,'gamma',mean(I), ...
         'tauF',tauF,'tauF_mean',mean(tauF,'omitnan'),'tauF_std',std(tauF,0,'omitnan'), ...
         'tauF_med',median(tauF,'omitnan'),'tauF_p10',prctile(tauF,10), ...
         'tauF_p90',prctile(tauF,90),'tauG',tauG, ...
         'tauG_mean',mean(tauG,'omitnan'),'tauG_med',median(tauG,'omitnan'));
end

function S = stats_from_intervals(IV, fs, Ntotal)
K=size(IV,1); T=Ntotal/fs; tauF=(IV(:,2)-IV(:,1)+1)/fs;
if K>=2, tauG=(IV(2:end,1)-IV(1:end-1,2)-1)/fs; else, tauG=[]; end
S=struct('N',Ntotal,'fs',fs,'Tsec',T,'Ne',K,'rateHz',K/T, ...
         'gamma',sum(tauF)/T,'tauF',tauF,'tauF_mean',mean(tauF,'omitnan'), ...
         'tauF_std',std(tauF,0,'omitnan'),'tauF_med',median(tauF,'omitnan'), ...
         'tauF_p10',prctile(tauF,10),'tauF_p90',prctile(tauF,90), ...
         'tauG',tauG,'tauG_mean',mean(tauG,'omitnan'),'tauG_med',median(tauG,'omitnan'));
end